swagger: '2.0'
info:
  version: 0.1.0
  title: Users API
  description: An API to demonstrate Swagger and Spring Boot
host: 'localhost:8080'
basePath: /api
schemes:
  - http
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header

paths:
  /authenticate:
    post:
      description: try to authenticate
      operationId: createAuthenticationToken
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: userAuth
          in: body
          required: true
          schema:
            $ref: '#/definitions/UserAuth'
      responses:
        200:
          description: 'authentication success'
          schema:
            type: object
            items:
              $ref: '#/definitions/JwtResponse'
        400:
          description: 'fail to authenticate'
          schema:
            type: string
  /users:
    post:
      security:
        - Bearer: []
      description: create a user
      operationId: createUser
      consumes:
        - application/json
      parameters:
        - name: userInput
          in: body
          required: true
          schema:
            $ref: '#/definitions/UserInput'
      responses:
        201:
          description: created
          schema:
            type: object
        400:
          description: 'You do not have necessary permissions to creat a user'
    get:
      security:
        - Bearer: []
      description: get user paramater
      operationId: getUsers
      produces:
        - application/json
      parameters:
        - name: startingIndex
          in: query
          default: 1
          required: false
          type: integer
        - name: numberOfUsers
          in: query
          default: 30
          required: false
          type: integer
      responses:
        200:
          description: 'success to get users'
          schema:
            type: array
            items:
              $ref: '#/definitions/UserToken'
        400:
          description: 'You do not have necessary permissions for the resource'
  /users/{email}:
    get:
      security:
        - Bearer: []
      description: ""
      operationId: getUserByID
      produces:
        - "application/json"
      parameters:
        - $ref: '#/parameters/emailParam'
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/UserToken"
        400:
          description: "You do not have necessary permissions for the resource"
    put:
      security:
        - Bearer: []
      description: ""
      operationId: updatePasswordByID
      produces:
        - "application/json"
      parameters:
        - $ref: '#/parameters/emailParam'
        - $ref: '#/parameters/passwordParam'
      responses:
        400:
          description: "You do not have necessary permissions for the resource"
    delete:
      security:
        - Bearer: []
      description: "This can only be done by the logged in user."
      operationId: deleteUserByID
      produces:
        - "application/json"
      parameters:
        - $ref: '#/parameters/emailParam'
      responses:
        200:
          description: "successful operation"
        400:
          description: 'You do not have necessary permissions for the resource'
definitions:
  User:
    type: object
    properties:
      email:
        type: string
  UserToken:
    allOf:
      - $ref: "#/definitions/User"
      - type: object
      - properties:
          role:
            type: string
  UserAuth:
    allOf:
      - $ref: "#/definitions/User"
      - type: object
      - properties:
          password:
            type: string
  UserInput:
    allOf:
      - $ref: "#/definitions/User"
      - $ref: "#/definitions/UserToken"
      - $ref: "#/definitions/UserAuth"
  JwtResponse:
    type: object
    properties:
      jwttoken:
        type: string
parameters:
  emailParam:
    name: email
    in: path
    description: "name that need to be updated"
    required: true
    type: string
  passwordParam:
    name: password
    in: query
    description: "Updated user object"
    required: true
    type: string