-- MySQL Script generated by MySQL Workbench
-- Fri Dec  6 17:03:15 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema amt_2
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `amt_2` ;

-- -----------------------------------------------------
-- Schema amt_2
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `amt_2` DEFAULT CHARACTER SET utf8 ;
USE `amt_2` ;

-- -----------------------------------------------------
-- Table `amt_2`.`user_entity`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `amt_2`.`users_entity` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `firstname` VARCHAR(45) NOT NULL,
  `lastname` VARCHAR(45) NOT NULL,
  `role` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`, `email`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
