version: '3'
services:
   db:
      build: ../images/mysql
      command: --default-authentication-plugin=mysql_native_password
      environment:
         MYSQL_ROOT_PASSWORD: admin
      ports:
         - "3306:3306"
   phpmyadmin:
      build: ../images/phpmyadmin
      environment:
         PMA_HOST: mysql
         MYSQL_ROOT_PASSWORD: admin
      ports:
         - "6060:80"
      depends_on:
         - db
   swag1:
      build: ../images/java_server_1
      ports:
        - "8080:8080"
      restart: on-failure
      links: 
        - db
   swag2:
      build: ../images/java_server_2
      ports:
         - "8081:8081"
      restart: on-failure
      links: 
         - db