version: '3'
services:
   mysql:
      build: ../images/mysql
      command: --default-authentication-plugin=mysql_native_password
      environment:
         MYSQL_ROOT_PASSWORD: admin
      ports:
         - "3306:3306"
   phpmyadmin:
      build: ../images/phpmyadmin
      environment:
         PMA_HOST: mysql
         MYSQL_ROOT_PASSWORD: admin
      ports:
         - "6060:80"
      links:
         - mysql:db
