swagger: '2.0'
info:
  version: 0.1.0
  title: User API
  description: An API to demonstrate Swagger and Spring Boot
host: 'localhost:8080'
basePath: /api
schemes:
  - http
paths:
  /user:
    post:
      description: create a user
      operationId: createUser
      consumes:
        - application/json
      parameters:
        - name: user
          in: body
          required: true
          schema:
            $ref: '#/definitions/User'
      responses:
        '201':
          description: created
          schema:
            type: object
    get:
      description: get user paramater
      operationId: getUsers
      produces:
        - application/json
      responses:
        '200':
          description: success
          schema:
            type: array
            items:
              $ref: '#/definitions/User'
definitions:
  User:
    type: object
    properties:
      firstname:
        type: string
      lastname:
        type: string
      role:
        type: string
      email:
        type: string
      password:
        type: string
