-- MySQL Script generated by MySQL Workbench
-- Wed Dec 11 02:10:37 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema amt_21
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `amt_21` ;

-- -----------------------------------------------------
-- Schema amt_21
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `amt_21` DEFAULT CHARACTER SET utf8 ;
USE `amt_21` ;

-- -----------------------------------------------------
-- Table `amt_21`.`user_entity`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `amt_21`.`user_entity` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `firstname` VARCHAR(45) NOT NULL,
  `lastname` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`, `email`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `amt_21`.`trail_entity`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `amt_21`.`trail_entity` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `length` INT NOT NULL,
  `description` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `amt_21`.`registration_entity`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `amt_21`.`registration_entity` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `idTrail` INT NOT NULL,
  `idUser` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
